### ISSUE TITLE
Epoch computations and time management

### ISSUE THREAD

**Issue by ChristopherRabotin** [OpenAstrodynamics/lox#1]
Hi Helge!

I saw that you're implementing time computations for astrodynamics in Rust. Time computations, as you know, is very error prone. I've actually spent a few years developing [hifitime](https://github.com/nyx-space/hifitime#features) which supports all time scales typically used in astrodynamics. You can find additional documentation (including for its Python bindings) on the MathSpec of Nyx Space (https://nyxspace.com/hifitime/intro/). It's thoroughly tested and formally verified. I don't want to be "that guy" but if you are interested in using that instead or rewriting it from scratch, I'd be happy to help!

As we've discussed a few times on Matrix, Nyx itself is also in active development (cf. https://github.com/nyx-space/nyx). I'm working on version 2, which should provide most functionality for using it for pre-flight analysis and start of operations.

Glad to see that you're having a look at Rust!

**Comment by helgee** [comment]
Hey Chris,

No worries, I am of course aware of your work (and impressed by it). This library is primarily meant as a vehicle/excuse for myself to explore and learn Rust which requires a certain amount of reinventing the wheel in my experience to develop real expertise. At this point, I would not feel comfortable at all trying to contribute to other people's projects, e.g., yours.

That being said, since it is still early days for rustic astrodynamics, the design space is largely unexplored and having several independent exploration missions probably would not hurt (at the cost of splitting resources).

**Comment by ChristopherRabotin** [comment]
Sounds good!

**Comment by ChristopherRabotin** [comment]
Hi there,

Your talk on Lox really good the world by storm, congrats!

At minute 37 of the talk, https://youtu.be/UETWW7l1Y0g?si=wyRaxNX7MmaRCblc&t=2266 , you mention that the TDB transformation in Hifitime is not accurate. Could you tell me more about that? Hifitime proposes both the ESA defined TDB transformation, as detailed in NaviPedia, and the simplified TDB transformation from NASA/NAIF marked as "Ephemeris Time" (ET). The ET transformation is used in ANISE to match the SPICE results to within machine precision. Hence, are you also stating that NASA's implementation is also wrong?

Thanks for your clarifications

**Comment by helgee** [comment]
Hi Chris,

Thanks for stopping by and congratulations on your successful landing. I am living vicariously through you folks at the moment!

**Bottom line up front:** hifitime is as accurate if not more so than lox-time. The justification for Lox existing remains the same: to further explore the design space. 

What I told @AngusGMorrison with respect to TDB transformations is that the one used by hifitime (and also by lox-time) is not the most accurate one in absolute terms because is does not take the state of the observer into account but is a good trade-off between accuracy and computational requirements. I also mentioned that I had trouble tracing the original source of this equation because neither ESA nor Orekit cite it properly. AFAICT it is from the "The Explanatory Supplement to the Astronomical Almanac".
If this came across as dissing hifitime, it is my fault and I apologise. I am sure that there are no problems with your code and plan to use ANISE for our validation tests going forward. I will check with Angus and then post a correction under the YouTube video.

**Comment by ChristopherRabotin** [comment]
That makes perfect sense, thanks. I definitely didn't try to find the original source for Navi Pedia. I was mostly worried that you'd found an important bug I wasn't aware of.

Ad Astra, and good work again on Lox!

**Comment by AngusGMorrison** [comment]
Hi @ChristopherRabotin. Sincere apologies for spreading confusion. I should have been better prepared for that question instead of reaching for something half-remembered under the spotlight. 🙏 Apparently I didn't reserve the right not to publicly embarrass myself after all!
